spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/olx
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8888
