spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          olx:
            client-id: 200136
            client-secret: tmq8thGaySN21iPx4ysbC2te7hpsgvn6BM6kJispef6DS6PK
            client-name: olx
            scope: [v2,read,write]
            provider: olx-provider
            redirect-uri: http://49.12.227.7:8095
            client-authentication-method: CLIENT_SECRET_BASIC
            authorization-grant-type: authorization_code
        provider:
          olx-provider:
            token-uri: https://www.olx.ro/api/open/oauth/token
            authorization-uri: https://www.olx.ro/oauth/authorize
            user-info-uri: https://www.olx.ro/api/partner/users/me
            user-name-attribute: name
    user:
      name: andrei123
      password: olx!@#
  datasource:
    url: jdbc:postgresql://localhost:5432/olx
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
server:
  servlet:
    session:
      cookie:
        http-only: false
  port: 8888
